

function ball(region) {
  const combinedList = { // liste de tout les pokemon contenue dans chaque ball
    HORRORBALL: [
        { name: "Branette", rarity: "R", frequency: 0.05263 },
        { name: "Ectoplasma", rarity: "R", frequency: 0.05263 },
        { name: "Yveltal", rarity: "E", frequency: 0.004 },
        { name: "Banshitrouye", rarity: "R", frequency: 0.05263 },
        { name: "Tutafeh", rarity: "C", frequency: 0.15789 },
        { name: "Brocelome", rarity: "P", frequency: 0.10526 },
        { name: "Desseliande", rarity: "R", frequency: 0.05263 },
        { name: "Funécire", rarity: "C", frequency: 0.15789 },
        { name: "Lugulabre", rarity: "R", frequency: 0.05263 },
        { name: "Melancolux", rarity: "C", frequency: 0.15789 },
        { name: "Parasect", rarity: "P", frequency: 0.10526 },
        { name: "Soporifik", rarity: "P", frequency: 0.10526 },
        { name: "Hypnomade", rarity: "R", frequency: 0.05263 },
        { name: "Skelenox", rarity: "C", frequency: 0.15789 },
        { name: "Noctunoir", rarity: "R", frequency: 0.05263 },
        { name: "Baudrive", rarity: "C", frequency: 0.15789 },
        { name: "Grodrive", rarity: "R", frequency: 0.05263 },
        { name: "Pitrouille", rarity: "C", frequency: 0.15789 },
        { name: "Paras", rarity: "P", frequency: 0.10526 },
        { name: "Monorpale", rarity: "C", frequency: 0.15789 },
        { name: "Dimocles", rarity: "P", frequency: 0.10526 },
        { name: "Exagide", rarity: "R", frequency: 0.05263 },
        { name: "Obalie_Horror", rarity: "L", frequency: 0.00002 }
    ],
    FORESTBALL: [
        { name: "Torterra", rarity: "R", frequency: 0.046 },
        { name: "Tortipouss", rarity: "C", frequency: 0.221 },
        { name: "Boskara", rarity: "P", frequency: 0.085 },
        { name: "Haydaim", rarity: "R", frequency: 0.046 },
        { name: "Chenipan", rarity: "C", frequency: 0.192 },
        { name: "Chrysacier", rarity: "P", frequency: 0.096 },
        { name: "Papilusion", rarity: "R", frequency: 0.042 },
        { name: "Grainipiot", rarity: "C", frequency: 0.138 },
        { name: "Vivaldaim", rarity: "C", frequency: 0.138 },
        { name: "Saquedeneu", rarity: "P", frequency: 0.085 },
        { name: "Aspicot", rarity: "C", frequency: 0.192 },
        { name: "Coconfort", rarity: "P", frequency: 0.096 },
        { name: "Dardargnan", rarity: "R", frequency: 0.042 },
        { name: "Pikachu", rarity: "E", frequency: 0.02 },
        { name: "Trompignon", rarity: "C", frequency: 0.192 },
        { name: "Rongrigou", rarity: "P", frequency: 0.085 },
        { name: "Rongourmand", rarity: "C", frequency: 0.138 },
        { name: "Pifeuil", rarity: "P", frequency: 0.085 },
        { name: "Tengalice", rarity: "R", frequency: 0.042 },
        { name: "Bouldeneu", rarity: "P", frequency: 0.085 },
        { name: "Ortide", rarity: "P", frequency: 0.085 },
        { name: "Rafflesia", rarity: "R", frequency: 0.042 },
        { name: "Scarhino", rarity: "R", frequency: 0.042 },
        { name: "Scarabrute", rarity: "R", frequency: 0.042 },
        { name: "Chapignon", rarity: "C", frequency: 0.138 },
        { name: "Manzai", rarity: "P", frequency: 0.085 },
        { name: "Simulacre", rarity: "R", frequency: 0.042 },
        { name: "Arcko", rarity: "C", frequency: 0.221 },
        { name: "Massko", rarity: "P", frequency: 0.085 },
        { name: "Jungko", rarity: "R", frequency: 0.046 },
        { name: "Tag-Tag", rarity: "P", frequency: 0.085 },
        { name: "Obalie_Forest", rarity: "L", frequency: 0.005 }
    ],
    CUTIEBALL: [
        { name: "Mew", rarity: "E", frequency: 0.045 },
        { name: "Obalie", rarity: "C", frequency: 0.155 },
        { name: "Tiplouf", rarity: "C", frequency: 0.155 },
        { name: "Azurill", rarity: "C", frequency: 0.155 },
        { name: "Togepi", rarity: "C", frequency: 0.155 },
        { name: "Teddiursa", rarity: "C", frequency: 0.155 },
        { name: "Voltoutou", rarity: "C", frequency: 0.155 },
        { name: "Caninos", rarity: "C", frequency: 0.155 },
        { name: "Goupix", rarity: "C", frequency: 0.155 },
        { name: "Evoli", rarity: "C", frequency: 0.155 },
        { name: "Lixy", rarity: "C", frequency: 0.155 },
        { name: "Pachirisu", rarity: "C", frequency: 0.155 },
        { name: "Chinchidou", rarity: "C", frequency: 0.155 },
        { name: "Bibichu", rarity: "C", frequency: 0.155 },
        { name: "Axoloto", rarity: "C", frequency: 0.155 },
        { name: "Nigirigon", rarity: "C", frequency: 0.155 },
        { name: "Tetampoule", rarity: "C", frequency: 0.155 },
        { name: "Pohm", rarity: "C", frequency: 0.155 },
        { name: "Marill", rarity: "P", frequency: 0.1 },
        { name: "Pohmotte", rarity: "P", frequency: 0.1 },
        { name: "Pohmarmotte", rarity: "R", frequency: 0.05 },
        { name: "Obalie_Mignon", rarity: "L", frequency: 0.003 }
    ],
    REPULSBALL: [
        { name: "Miamiasme", rarity: "C", frequency: 0.15 },
        { name: "Miasmax", rarity: "P", frequency: 0.1 },
        { name: "Tarinorme", rarity: "R", frequency: 0.05 },
        { name: "Golgopathe", rarity: "R", frequency: 0.05 },
        { name: "Excelangue", rarity: "P", frequency: 0.1 },
        { name: "Crapustule", rarity: "R", frequency: 0.05 },
        { name: "Chaffreux", rarity: "P", frequency: 0.1 },
        { name: "Ratentif", rarity: "C", frequency: 0.15 },
        { name: "Miradar", rarity: "P", frequency: 0.1 },
        { name: "Lippoutou", rarity: "R", frequency: 0.05 },
        { name: "Balignon", rarity: "C", frequency: 0.15 },
        { name: "Limonde", rarity: "C", frequency: 0.15 },
        { name: "Grotadmorv", rarity: "P", frequency: 0.1 },
        { name: "Barpau", rarity: "R", frequency: 0.05 },
        { name: "Amovénus", rarity: "E", frequency: 0.02 },
        { name: "Manglouton", rarity: "C", frequency: 0.15 },
        { name: "Argouste", rarity: "P", frequency: 0.1 },
        { name: "Terracol", rarity: "C", frequency: 0.15 },
        { name: "Terracruel", rarity: "P", frequency: 0.1 },
        { name: "Lippouti", rarity: "C", frequency: 0.15 },
        { name: "Insolourdo", rarity: "C", frequency: 0.15 },
        { name: "Deusolourdo", rarity: "P", frequency: 0.1 },
        { name: "Tarinor", rarity: "C", frequency: 0.15 },
        { name: "Obalie_Moche", rarity: "L", frequency: 0.005 }
    ],
    CARNIVOBALL: [
        { name: "Obalie", rarity: "L", frequency: 0.005 },
        { name: "Ecremeuh", rarity: "R", frequency: 0.05 },
        { name: "Tauros", rarity: "R", frequency: 0.05 },
        { name: "Frison", rarity: "R", frequency: 0.05 },
        { name: "Palarticho", rarity: "R", frequency: 0.05 },
        { name: "Roitiflam", rarity: "R", frequency: 0.05 },
        { name: "Gamblast", rarity: "P", frequency: 0.1 },
        { name: "Krabboss", rarity: "P", frequency: 0.1 },
        { name: "Poissoroy", rarity: "P", frequency: 0.1 },
        { name: "Fragroin", rarity: "P", frequency: 0.1 },
        { name: "Grotichon", rarity: "P", frequency: 0.1 },
        { name: "Canarticho", rarity: "P", frequency: 0.1 },
        { name: "Lovdisc", rarity: "P", frequency: 0.1 },
        { name: "Bargantua", rarity: "P", frequency: 0.1 },
        { name: "Craparoi", rarity: "C", frequency: 0.15 },
        { name: "Gourmelet", rarity: "C", frequency: 0.15 },
        { name: "Gruikui", rarity: "C", frequency: 0.15 },
        { name: "Krabby", rarity: "C", frequency: 0.15 },
        { name: "Magikarp", rarity: "C", frequency: 0.15 },
        { name: "Moumouton", rarity: "C", frequency: 0.15 },
        { name: "Poissirene", rarity: "C", frequency: 0.15 },
        { name: "Roucool", rarity: "C", frequency: 0.15 },
        { name: "Tiboudet", rarity: "C", frequency: 0.15 },
        { name: "Flingouste", rarity: "C", frequency: 0.15 },
        { name: "Moumouflon", rarity: "P", frequency: 0.1 }
      ],
      VEGGIEBALL: [
        { name: "Obalie_Vegan", rarity: "L", frequency: 0.005 },
        { name: "Pomdrapi", rarity: "R", frequency: 0.05 },
        { name: "Dratatin", rarity: "R", frequency: 0.05 },
        { name: "Sucreine", rarity: "R", frequency: 0.05 },
        { name: "Ceriflor", rarity: "R", frequency: 0.05 },
        { name: "Tropius", rarity: "R", frequency: 0.05 },
        { name: "Charmilly", rarity: "P", frequency: 0.1 },
        { name: "Scovilain", rarity: "P", frequency: 0.1 },
        { name: "Arboliva", rarity: "P", frequency: 0.1 },
        { name: "Candine", rarity: "P", frequency: 0.1 },
        { name: "Guérilande", rarity: "P", frequency: 0.1 },
        { name: "Ceribou", rarity: "C", frequency: 0.15 },
        { name: "Croquine", rarity: "C", frequency: 0.15 },
        { name: "Cremy", rarity: "C", frequency: 0.15 },
        { name: "Noeunoeuf", rarity: "P", frequency: 0.1 },
        { name: "Olivado", rarity: "P", frequency: 0.1 },
        { name: "Mystherbe", rarity: "C", frequency: 0.15 },
        { name: "Verpom", rarity: "C", frequency: 0.15 },
        { name: "Apitrini", rarity: "C", frequency: 0.15 },
        { name: "Olivini", rarity: "C", frequency: 0.15 },
        { name: "Pimito", rarity: "C", frequency: 0.15 }
      ],
      SAFARIBALL: [
        { name: "Hélionceau", rarity: "C", frequency: 0.15 },
        { name: "Némélios", rarity: "P", frequency: 0.1 },
        { name: "Doduo", rarity: "C", frequency: 0.15 },
        { name: "Dodrio", rarity: "P", frequency: 0.1 },
        { name: "Zebibron", rarity: "P", frequency: 0.1 },
        { name: "Zeblitz", rarity: "R", frequency: 0.05 },
        { name: "Girafig", rarity: "R", frequency: 0.05 },
        { name: "Scorplane", rarity: "P", frequency: 0.1 },
        { name: "Scorvol", rarity: "R", frequency: 0.05 },
        { name: "Nidoran_M", rarity: "C", frequency: 0.15 },
        { name: "Nidoran_F", rarity: "C", frequency: 0.15 },
        { name: "Nidorino", rarity: "P", frequency: 0.1 },
        { name: "Nidorina", rarity: "P", frequency: 0.1 },
        { name: "Ouisticram", rarity: "C", frequency: 0.15 },
        { name: "Chimpenfeu", rarity: "P", frequency: 0.1 },
        { name: "Simiabraz", rarity: "R", frequency: 0.05 },
        { name: "Ferossinge", rarity: "C", frequency: 0.15 },
        { name: "Colossinge", rarity: "P", frequency: 0.1 },
        { name: "Courrousinge", rarity: "R", frequency: 0.05 },
        { name: "Hippopotas", rarity: "C", frequency: 0.15 },
        { name: "Hippodocus", rarity: "P", frequency: 0.1 },
        { name: "Feunard", rarity: "R", frequency: 0.05 },
        { name: "Phanpy", rarity: "C", frequency: 0.15 },
        { name: "Donphan", rarity: "P", frequency: 0.1 },
        { name: "Fort-Ivoire", rarity: "R", frequency: 0.05 },
        { name: "Kangourex", rarity: "R", frequency: 0.05 },
        { name: "Ossatueur", rarity: "C", frequency: 0.15 },
        { name: "Osselait", rarity: "P", frequency: 0.1 },
        { name: "Obalie_Safari", rarity: "L", frequency: 0.004 }
      ],
      WAIFUBALL: [
        { name: "Lockpin", rarity: "R", frequency: 0.066 },
        { name: "Laporeille", rarity: "P", frequency: 0.133 },
        { name: "Gardevoir", rarity: "R", frequency: 0.066 },
        { name: "Meloetta", rarity: "E", frequency: 0.133 },
        { name: "Sucreine", rarity: "R", frequency: 0.066 },
        { name: "Cancrelove", rarity: "E", frequency: 0.003 },
        { name: "Fragilady", rarity: "R", frequency: 0.066 },
        { name: "Nidoqueen", rarity: "R", frequency: 0.066 },
        { name: "Scrutella", rarity: "R", frequency: 0.066 },
        { name: "Mesmérella", rarity: "P", frequency: 0.133 },
        { name: "Sidérella", rarity: "C", frequency: 0.2 },
        { name: "Forgerette", rarity: "C", frequency: 0.2 },
        { name: "Forgella", rarity: "P", frequency: 0.1 },
        { name: "Forgelina", rarity: "R", frequency: 0.066 },
        { name: "Obalie_Waifu", rarity: "L", frequency: 0.001 }
      ],
      HUSBANDOBALL: [
        { name: "Gallame", rarity: "R", frequency: 0.05 },
        { name: "Bétochef", rarity: "R", frequency: 0.05 },
        { name: "Charpenti", rarity: "C", frequency: 0.15 },
        { name: "Ouvrifier", rarity: "P", frequency: 0.1 },
        { name: "Judokrak", rarity: "R", frequency: 0.05 },
        { name: "Karaclée", rarity: "R", frequency: 0.05 },
        { name: "Mouscoto", rarity: "E", frequency: 0.01 },
        { name: "Coudlangue", rarity: "R", frequency: 0.05 },
        { name: "Nidoking", rarity: "R", frequency: 0.05 },
        { name: "Pyrobut", rarity: "R", frequency: 0.05 },
        { name: "Braségali", rarity: "R", frequency: 0.05 },
        { name: "Kapoera", rarity: "P", frequency: 0.1 },
        { name: "Makuhita", rarity: "P", frequency: 0.1 },
        { name: "Meditikka", rarity: "P", frequency: 0.1 },
        { name: "Charmina", rarity: "R", frequency: 0.05 },
        { name: "Brutalibré", rarity: "R", frequency: 0.05 },
        { name: "Marshadow", rarity: "E", frequency: 0.01 },
        { name: "Obalie_Husbando", rarity: "L", frequency: 0.004 }
      ],
      POINGBALL: [
        { name: "Machoc", rarity: "C", frequency: 0.2 },
        { name: "Machopeur", rarity: "P", frequency: 0.1 },
        { name: "Mackogneur", rarity: "R", frequency: 0.05 },
        { name: "Gravalanch", rarity: "P", frequency: 0.1 },
        { name: "Wushours", rarity: "E", frequency: 0.02 },
        { name: "Shifours", rarity: "E", frequency: 0.02 },
        { name: "Chelours", rarity: "R", frequency: 0.05 },
        { name: "Ursaring", rarity: "R", frequency: 0.05 },
        { name: "Hariyama", rarity: "R", frequency: 0.05 },
        { name: "Monaflémit", rarity: "R", frequency: 0.05 },
        { name: "Paume de fer", rarity: "R", frequency: 0.05 },
        { name: "Shaofouine", rarity: "R", frequency: 0.05 },
        { name: "Polagriffe", rarity: "R", frequency: 0.05 },
        { name: "Gorythmic", rarity: "R", frequency: 0.05 },
        { name: "Rhinastoc", rarity: "R", frequency: 0.05 },
        { name: "Tygnon", rarity: "P", frequency: 0.1 },
        { name: "Debugant", rarity: "P", frequency: 0.1 },
        { name: "Lucario", rarity: "R", frequency: 0.05 },
        { name: "Riolu", rarity: "C", frequency: 0.2 },
        { name: "Crabagarre", rarity: "C", frequency: 0.2 },
        { name: "Crabominable", rarity: "P", frequency: 0.1 },
        { name: "Capumain", rarity: "C", frequency: 0.2 },
        { name: "Capidextre", rarity: "P", frequency: 0.1 },
        { name: "Tartard", rarity: "R", frequency: 0.05 },
        { name: "Têtarte", rarity: "P", frequency: 0.1 },
        { name: "Kicklee", rarity: "P", frequency: 0.1 },
        { name: "Pandespiègle", rarity: "C", frequency: 0.2 },
        { name: "Pandarbare", rarity: "R", frequency: 0.05 },
        { name: "Poulpaf", rarity: "C", frequency: 0.2 },
        { name: "Krakos", rarity: "P", frequency: 0.1 },
        { name : "Melmeltal" , rarity : "E" , frequency : 0.02 },
        { name : "Obalie_Poing" , rarity : "L" , frequency : 0.006 },
      ],
      SMALLBALL: [
        { name: "Flabébé", rarity: "C", frequency: 0.11214 },
        { name: "Statitik", rarity: "C", frequency: 0.11214 },
        { name: "Bombydou", rarity: "C", frequency: 0.11214 },
        { name: "cosmog", rarity: "E", frequency: 0.006 },
        { name: "Théffroi", rarity: "C", frequency: 0.11214 },
        { name: "Taupiqueur", rarity: "C", frequency: 0.11214 },
        { name: "Natu", rarity: "P", frequency: 0.09677 },
        { name: "Rozbouton", rarity: "P", frequency: 0.09677 },
        { name: "Cheniti", rarity: "C", frequency: 0.11214 },
        { name: "Korillon", rarity: "R", frequency: 0.0566 },
        { name: "Floette", rarity: "C", frequency: 0.11214 },
        { name: "Fluvetin", rarity: "C", frequency: 0.11214 },
        { name: "Dedenne", rarity: "C", frequency: 0.11214 },
        { name: "Froussardine", rarity: "C", frequency: 0.11214 },
        { name: "Spododo", rarity: "C", frequency: 0.11214 },
        { name: "Magnéti", rarity: "C", frequency: 0.11214 },
        { name: "Pichu", rarity: "P", frequency: 0.09677 },
        { name: "Mélo", rarity: "P", frequency: 0.09677 },
        { name: "Toudoudou", rarity: "P", frequency: 0.09677 },
        { name: "Gribouraigne", rarity: "C", frequency: 0.11214 },
        { name: "Meltan", rarity: "E", frequency: 0.006 },
        { name: "Morpeko", rarity: "P", frequency: 0.09677 },
        { name: "Obalie_Small", rarity: "L", frequency: 0.004}
      ],
      GEOBALL: [
        { name: "Nosferapti", rarity: "C", frequency: 0.125 },
        { name: "Nosferalto", rarity: "P", frequency: 0.0833 },
        { name: "Nostenfer", rarity: "R", frequency: 0.0556 },
        { name: "Sonistrelle", rarity: "P", frequency: 0.0833 },
        { name: "Bruyverne", rarity: "R", frequency: 0.0556 },
        { name: "Chovsourir", rarity: "C", frequency: 0.125 },
        { name: "Rhinolove", rarity: "P", frequency: 0.0833 },
        { name: "Rototaupe", rarity: "C", frequency: 0.125 },
        { name: "Minotaupe", rarity: "R", frequency: 0.0556 },
        { name: "Sapereau", rarity: "C", frequency: 0.125 },
        { name: "Excavarenne", rarity: "P", frequency: 0.0833 },
        { name: "Nodulithe", rarity: "C", frequency: 0.125 },
        { name: "Géolithe", rarity: "P", frequency: 0.0833 },
        { name: "Gigalithe", rarity: "R", frequency: 0.0556 },
        { name: "Racaillou", rarity: "C", frequency: 0.125 },
        { name: "Grolem", rarity: "R", frequency: 0.0556 },
        { name: "Opermine", rarity: "C", frequency: 0.125 },
        { name: "Triopikeur", rarity: "R", frequency: 0.0556 },
        { name: "Onix", rarity: "P", frequency: 0.0833 },
        { name: "Steelix", rarity: "R", frequency: 0.0556 },
        { name: "Strassie", rarity: "P", frequency: 0.0833 },
        { name: "Diancie", rarity: "E", frequency: 0.01 },
        { name: "Griknot", rarity: "C", frequency: 0.125 },
        { name: "Carmache", rarity: "P", frequency: 0.0833 },
        { name: "Carchacrok", rarity: "R", frequency: 0.0556 },
        { name: "Grindur", rarity: "C", frequency: 0.125 },
        { name: "Noacier", rarity: "P", frequency: 0.0833 },
        { name: "Ténéfix", rarity: "R", frequency: 0.0556 },
        { name: "Obalie_Grotte", rarity: "L", frequency: 0.004}
      ],
      MAGIEBALL: [
        { name: "Abra", rarity: "C", frequency: 0.14285 },
        { name: "Kadabra", rarity: "P", frequency: 0.07142 },
        { name: "Alakazam", rarity: "R", frequency: 0.03571 },
        { name: "Mentali", rarity: "R", frequency: 0.03571 },
        { name: "Mime Jr.", rarity: "P", frequency: 0.07142 },
        { name: "Mr Mime.", rarity: "R", frequency: 0.03571 },
        { name: "Psystigri", rarity: "C", frequency: 0.14285 },
        { name: "Mistigrix", rarity: "P", frequency: 0.07142 },
        { name: "Wimessir", rarity: "P", frequency: 0.07142 },
        { name: "Flotillon", rarity: "C", frequency: 0.14285 },
        { name: "Cléopsytra", rarity: "P", frequency: 0.07142 },
        { name: "Feunnec", rarity: "C", frequency: 0.14285 },
        { name: "Roussil", rarity: "P", frequency: 0.07142 },
        { name: "Goupelin", rarity: "R", frequency: 0.03571 },
        { name: "Qulbutoké", rarity: "R", frequency: 0.03571 },
        { name: "Hoopa", rarity: "E", frequency: 0.001 },
        { name: "Farigiraf", rarity: "P", frequency: 0.07142 },
        { name: "Obalie_Magie", rarity: "L", frequency: 0.0004},
      ],
      PIAFBALL : [
        { name: "Minisange", rarity: "C", frequency: 0.0588 },
        { name: "Bleusaille", rarity: "P", frequency: 0.0294 },
        { name: "Corvaillus", rarity: "R", frequency: 0.0196 },
        { name: "Zapétrel", rarity: "C", frequency: 0.0588 },
        { name: "Fulgulairo", rarity: "R", frequency: 0.0196 },
        { name: "Passerouge", rarity: "C", frequency: 0.0588 },
        { name: "Braisillon", rarity: "P", frequency: 0.0294 },
        { name: "Flambusard", rarity: "R", frequency: 0.0196 },
        { name: "Roucarnage", rarity: "P", frequency: 0.0294 },
        { name: "Roucoups", rarity: "R", frequency: 0.0196 },
        { name: "Piafabec", rarity: "C", frequency: 0.0588 },
        { name: "Rapasdepic", rarity: "P", frequency: 0.0294 },
        { name: "Hoothoot", rarity: "C", frequency: 0.0588 },
        { name: "Noarfang", rarity: "R", frequency: 0.0196 },
        { name: "Nirondelle", rarity: "C", frequency: 0.0588 },
        { name: "Hélédelle", rarity: "P", frequency: 0.0294 },
        { name: "Etourmi", rarity: "C", frequency: 0.0588 },
        { name: "Etourvol", rarity: "P", frequency: 0.0294 },
        { name: "Etouraptor", rarity: "R", frequency: 0.0196 },
        { name: "Poichigeon", rarity: "C", frequency: 0.0588 },
        { name: "Colombeau", rarity: "P", frequency: 0.0294 },
        { name: "Déflaisan", rarity: "R", frequency: 0.0196 },
        { name: "Furaiglon", rarity: "P", frequency: 0.0294 },
        { name: "Gueriaigle", rarity: "R", frequency: 0.0196 },
        { name: "Picassaut", rarity: "C", frequency: 0.0588 },
        { name: "Piclairon", rarity: "P", frequency: 0.0294 },
        { name: "Bazoucan", rarity: "R", frequency: 0.0196 },
        { name: "Tapatoès", rarity: "P", frequency: 0.0294 },
        { name: "Lestombaile", rarity: "R", frequency: 0.0196 },
        { name: "Flamenroule", rarity: "P", frequency: 0.0294 },
        { name: "Obalie_Voliere", rarity: "L", frequency: 0.002 } 
      ],
      FOSSILBALL : [
        { name: "Kabuto", rarity: "C", frequency: 0.09 },
        { name: "Kabutops", rarity: "P", frequency: 0.04 },
        { name: "Amonita", rarity: "C", frequency: 0.09 },
        { name: "Amonistar", rarity: "P", frequency: 0.04 },
        { name: "Ptéra", rarity: "R", frequency: 0.02 },
        { name: "Lilia", rarity: "P", frequency: 0.04 },
        { name: "Vacilys", rarity: "R", frequency: 0.02 },
        { name: "Anorith", rarity: "C", frequency: 0.09 },
        { name: "Armaldo", rarity: "P", frequency: 0.04 },
        { name: "Kranidos", rarity: "C", frequency: 0.09 },
        { name: "Charkos", rarity: "P", frequency: 0.04 },
        { name: "Dinoclier", rarity: "C", frequency: 0.09 },
        { name: "Bastiodon", rarity: "P", frequency: 0.04 },
        { name: "Arkéapti", rarity: "C", frequency: 0.09 },
        { name: "Aéroptéryx", rarity: "P", frequency: 0.04 },
        { name: "Carapagos", rarity: "C", frequency: 0.09 },
        { name: "Mégapagos", rarity: "P", frequency: 0.04 },
        { name: "Ptyranidur", rarity: "C", frequency: 0.09 },
        { name: "Rexilius", rarity: "R", frequency: 0.02 },
        { name: "Amagara", rarity: "P", frequency: 0.04 },
        { name: "Dragmara", rarity: "R", frequency: 0.02 },
        { name: "Galvagon", rarity: "C", frequency: 0.09 },
        { name: "Galvagia", rarity: "C", frequency: 0.09 },
        { name: "Hydragon", rarity: "P", frequency: 0.04 },
        { name: "Hydragla", rarity: "P", frequency: 0.04 },
        { name: "Relicanth", rarity: "R", frequency: 0.02 },
        { name: "Rugit-Lune", rarity: "R", frequency: 0.02 },
        { name: "Hurle-Queue", rarity: "R", frequency: 0.02 },
        { name: "Fongus-Furie", rarity: "R", frequency: 0.02 },
        { name: "Rampe-Ailes", rarity: "R", frequency: 0.02 },
        { name: "Hachécateur", rarity: "R", frequency: 0.02 },
        { name: "Farfurex", rarity: "R", frequency: 0.02 },
        { name: "Obalie_Fossil", rarity: "L", frequency: 0.003 }
      ],
      PETBALL :  [
        { name: "Arcanin", rarity: "R", frequency: 0.05263 },
        { name: "Luxray", rarity: "R", frequency: 0.05263 },
        { name: "Luxio", rarity: "P", frequency: 0.10526 },
        { name: "Dynavolt", rarity: "C", frequency: 0.31579 },
        { name: "Elecsprint", rarity: "R", frequency: 0.05263 },
        { name: "Ponchiot", rarity: "C", frequency: 0.15789 },
        { name: "Ponchien", rarity: "P", frequency: 0.10526 },
        { name: "Mastouffe", rarity: "R", frequency: 0.05263 },
        { name: "Trousselin", rarity: "P", frequency: 0.10526 },
        { name: "Miaouss", rarity: "C", frequency: 0.15789 },
        { name: "Persian", rarity: "P", frequency: 0.10526 },
        { name: "Chaglam", rarity: "C", frequency: 0.15789 },
        { name: "Chacripan", rarity: "P", frequency: 0.10526 },
        { name: "Léopardus", rarity: "P", frequency: 0.10526 },
        { name: "Flamiaou", rarity: "C", frequency: 0.15789 },
        { name: "Matoufeu", rarity: "P", frequency: 0.10526 },
        { name: "Félinferno", rarity: "R", frequency: 0.05263 },
        { name: "Yuyu", rarity: "E", frequency: 0.05263 },
        { name: "Motisma", rarity: "R", frequency: 0.02449 },
        { name: "Motisma Four", rarity: "R", frequency: 0.02449 },
        { name: "Motisma Machine a laver", rarity: "R", frequency: 0.02449 },
        { name: "Motisma Tondeuse", rarity: "R", frequency: 0.02449 },
        { name: "Motisma Frigo", rarity: "R", frequency: 0.02449 },
        { name: "Motisma Ventilateur", rarity: "R", frequency: 0.02449 },
        { name: "Mr. Mime", rarity: "R", frequency: 0.05263 },
        { name: "Snubull", rarity: "C", frequency: 0.15789 },
        { name: "Granbull", rarity: "P", frequency: 0.10526 },
        { name: "Couafarel", rarity: "P", frequency: 0.10526 },
        { name: "Pashmilla", rarity: "P", frequency: 0.10526 },
        { name: "Obalie_Domestique", rarity: "L", frequency: 0.001 }
      ],
      AMAZONIEBALL : [
        { name: "Tadmorv", rarity: "C", frequency: 0.04348 },
        { name: "Arbok", rarity: "P", frequency: 0.07407 },
        { name: "Abo", rarity: "C", frequency: 0.04348 },
        { name: "Avaltout", rarity: "R", frequency: 0.09091 },
        { name: "Gloupti", rarity: "P", frequency: 0.07407 },
        { name: "Cradopaud", rarity: "C", frequency: 0.04348 },
        { name: "Coatox", rarity: "R", frequency: 0.09091 },
        { name: "Séviper", rarity: "R", frequency: 0.09091 },
        { name: "Qwilfish", rarity: "P", frequency: 0.07407 },
        { name: "Vorastérie", rarity: "C", frequency: 0.04348 },
        { name: "Prédastérie", rarity: "P", frequency: 0.07407 },
        { name: "Mimigal", rarity: "C", frequency: 0.04348 },
        { name: "Migalos", rarity: "P", frequency: 0.07407 },
        { name: "Venipatte", rarity: "C", frequency: 0.04348 },
        { name: "Scobolide", rarity: "P", frequency: 0.07407 },
        { name: "Brutapode", rarity: "R", frequency: 0.09091 },
        { name: "Moufouette", rarity: "C", frequency: 0.04348 },
        { name: "Moufflair", rarity: "P", frequency: 0.07407 },
        { name: "Drascore", rarity: "R", frequency: 0.09091 },
        { name: "Rapion", rarity: "C", frequency: 0.04348 },
        { name: "Chétiflor", rarity: "C", frequency: 0.04348 },
        { name: "Boustiflor", rarity: "P", frequency: 0.07407 },
        { name: "Empiflor", rarity: "R", frequency: 0.09091 },
        { name: "Vortente", rarity: "R", frequency: 0.09091 },
        { name: "Gaulet", rarity: "R", frequency: 0.09091 },
        { name: "Khélocrok", rarity: "C", frequency: 0.04348 },
        { name: "Torgamord", rarity: "P", frequency: 0.07407 },
        { name: "Obalie_Amazonie", rarity: "L", frequency: 0.003 }
    ],
    SNACKBALL  : [
        { name: "Selutin", rarity: "C", frequency: 0.1579 },
        { name: "Amassel", rarity: "P", frequency: 0.1052 },
        { name: "Gigansel", rarity: "R", frequency: 0.0526 },
        { name: "Patachiot", rarity: "C", frequency: 0.1579 },
        { name: "Briochien", rarity: "P", frequency: 0.1052 },
        { name: "Cremy", rarity: "C", frequency: 0.1579 },
        { name: "Charmilly", rarity: "P", frequency: 0.1052 },
        { name: "Sorbébé", rarity: "C", frequency: 0.1579 },
        { name: "Sorboul", rarity: "P", frequency: 0.1052 },
        { name: "Sorbouboul", rarity: "R", frequency: 0.0526 },
        { name: "Sucroquin", rarity: "C", frequency: 0.1579 },
        { name: "Cupcanaille", rarity: "P", frequency: 0.1052 },
        { name: "Goinfrex", rarity: "P", frequency: 0.1052 },
        { name: "Ronflex", rarity: "R", frequency: 0.0526 },
        { name: "Engloutyran", rarity: "E", frequency: 0.0263 },
        { name: "Polthégeist", rarity: "R", frequency: 0.0526 },
        { name: "Queue de Ramoloss", rarity: "E", frequency: 0.0263 },
        { name: "Obalie_Miam", rarity: "L", frequency: 0.0002 }
    ],
    RAPIDBALL : [
        { name: "Deoxys", rarity: "E", frequency: 0.05556 },
        { name: "Voltali", rarity: "R", frequency: 0.11111 },
        { name: "Amphinobi", rarity: "R", frequency: 0.11111 },
        { name: "Sharpedo", rarity: "R", frequency: 0.11111 },
        { name: "Yanmega", rarity: "R", frequency: 0.11111 },
        { name: "Drattak", rarity: "R", frequency: 0.11111 },
        { name: "Cizayox", rarity: "R", frequency: 0.11111 },
        { name: "Limaspeed", rarity: "P", frequency: 0.13889 },
        { name: "Musteflot", rarity: "P", frequency: 0.13889 },
        { name: "Galopa", rarity: "P", frequency: 0.13889 },
        { name: "Carvanha", rarity: "P", frequency: 0.13889 },
        { name: "Yanma", rarity: "P", frequency: 0.13889 },
        { name: "Linéon", rarity: "P", frequency: 0.13889 },
        { name: "Insecateur", rarity: "P", frequency: 0.13889 },
        { name: "Statitik", rarity: "C", frequency: 0.16667 },
        { name: "Stari", rarity: "C", frequency: 0.16667 },
        { name: "Ponyta", rarity: "C", frequency: 0.16667 },
        { name: "Fulgudog", rarity: "C", frequency: 0.16667 },
        { name: "Flambino", rarity: "C", frequency: 0.16667 },
        { name: "Lapyro", rarity: "C", frequency: 0.16667 },
        { name: "Mustebouee", rarity: "C", frequency: 0.16667 },
        { name: "Zeraora", rarity: "E", frequency: 0.05556 },
        { name: "Obalie_Vitesse", rarity: "L", frequency: 0.01}
    ],
    VOLCANOBALL : [
        { name: "Volcaropod", rarity: "P", frequency: 0.201 },
        { name: "Limagma", rarity: "C", frequency: 0.225 },
        { name: "Heatran", rarity: "E", frequency: 0.0428 },
        { name: "Sulfura", rarity: "E", frequency: 0.0428 },
        { name: "Chartor", rarity: "R", frequency: 0.138 },
        { name: "Héricendre", rarity: "C", frequency: 0.201 },
        { name: "Feurisson", rarity: "P", frequency: 0.086 },
        { name: "Typhlosion", rarity: "R", frequency: 0.138 },
        { name: "Charmallot", rarity: "P", frequency: 0.201 },
        { name: "Camerupt", rarity: "R", frequency: 0.138 },
        { name: "Malosse", rarity: "C", frequency: 0.225 },
        { name: "Démolosse", rarity: "P", frequency: 0.086 },
        { name: "Pyroli", rarity: "R", frequency: 0.138 },
        { name: "Magby", rarity: "C", frequency: 0.225 },
        { name: "Magmar", rarity: "P", frequency: 0.086 },
        { name: "Maganon", rarity: "R", frequency: 0.138 },
        { name: "Pyronille", rarity: "C", frequency: 0.225 },
        { name: "Pyrax", rarity: "R", frequency: 0.138 },
        { name: "Darumarond", rarity: "C", frequency: 0.201 },
        { name: "Darumacho", rarity: "P", frequency: 0.086 },
        { name: "Aflamanoir", rarity: "R", frequency: 0.138 },
        { name: "Charbi", rarity: "C", frequency: 0.225 },
        { name: "Wagomine", rarity: "P", frequency: 0.086 },
        { name: "Anthracite", rarity: "R", frequency: 0.138 },
        { name: "Grillepattes", rarity: "C", frequency: 0.225 },
        { name: "Scolopendre", rarity: "P", frequency: 0.086 },
        { name: "Galifeu", rarity: "P", frequency: 0.201 },
        { name: "Salamèche", rarity: "C", frequency: 0.201 },
        { name: "Reptincel", rarity: "P", frequency: 0.086 },
        { name: "Dracaufeu", rarity: "R", frequency: 0.138 },
        { name: "Obalie_Chaud", rarity: "L", frequency: 0.001 }
    ],
    RYTHMBALL: [
        { name: "Meloetta", rarity: "E", frequency: 0.05883 },
        { name: "Pijako", rarity: "P", frequency: 0.10588 },
        { name: "Chuchmur", rarity: "C", frequency: 0.22353 },
        { name: "Ramboum", rarity: "P", frequency: 0.10588 },
        { name: "Brouhabam", rarity: "R", frequency: 0.07059 },
        { name: "Crikzik", rarity: "C", frequency: 0.22353 },
        { name: "Mélokrik", rarity: "P", frequency: 0.10588 },
        { name: "Eoko", rarity: "R", frequency: 0.07059 },
        { name: "Nenupiot", rarity: "C", frequency: 0.22353 },
        { name: "Lombre", rarity: "P", frequency: 0.10588 },
        { name: "Ludicolo", rarity: "R", frequency: 0.07059 },
        { name: "Tarsal", rarity: "C", frequency: 0.22353 },
        { name: "Kirlia", rarity: "P", frequency: 0.10588 },
        { name: "Rondoudou", rarity: "P", frequency: 0.10588 },
        { name: "Grodoudou", rarity: "R", frequency: 0.07059 },
        { name: "Toudoudou", rarity: "C", frequency: 0.22353 },
        { name: "Rosabyss", rarity: "P", frequency: 0.10588 },
        { name: "Cryptéro", rarity: "R", frequency: 0.07059 },
        { name: "Tarpaud", rarity: "R", frequency: 0.07059 },
        { name: "Tritonde", rarity: "C", frequency: 0.22353 },
        { name: "Ampibidou", rarity: "R", frequency: 0.07059 },
        { name: "Ouistempo", rarity: "C", frequency: 0.22222 },
        { name: "Badabouin", rarity: "P", frequency: 0.11111 },
        { name: "Gorythmic", rarity: "R", frequency: 0.07407 },
        { name: "Flamigator", rarity: "R", frequency: 0.07407 },
        { name: "Obalie_Musique", rarity: "L", frequency: 0.002 }
    ],
    BUBBLEBALL: [
        { name: "Ecayon", rarity: "C", frequency: 0.18 },
        { name: "Luminéon", rarity: "P", frequency: 0.1 },
        { name: "Serpang", rarity: "P", frequency: 0.1 },
        { name: "Walmer", rarity: "C", frequency: 0.18 },
        { name: "Wailord", rarity: "R", frequency: 0.09 },
        { name: "Coquiperl", rarity: "C", frequency: 0.18 },
        { name: "Colhomard", rarity: "R", frequency: 0.09 },
        { name: "Kokiyas", rarity: "C", frequency: 0.18 },
        { name: "Crustabri", rarity: "P", frequency: 0.1 },
        { name: "Hypotrempe", rarity: "C", frequency: 0.18 },
        { name: "Octillery", rarity: "R", frequency: 0.09 },
        { name: "Babimanta", rarity: "C", frequency: 0.18 },
        { name: "Rémoraid", rarity: "C", frequency: 0.18 },
        { name: "Barloche", rarity: "C", frequency: 0.18 },
        { name: "Barbicha", rarity: "P", frequency: 0.1 },
        { name: "Caratroc", rarity: "R", frequency: 0.09 },
        { name: "Ecrapince", rarity: "C", frequency: 0.18 },
        { name: "Phione", rarity: "E", frequency: 0.03 },
        { name: "Manaphy", rarity: "E", frequency: 0.03 },
        { name: "Corayon", rarity: "P", frequency: 0.1 },
        { name: "Anchwatt", rarity: "C", frequency: 0.18 },
        { name: "Lampéroie", rarity: "P", frequency: 0.1 },
        { name: "Ohmassacre", rarity: "R", frequency: 0.09 },
        { name: "Wattapik", rarity: "C", frequency: 0.18 },
        { name: "Ptitard", rarity: "C", frequency: 0.18 },
        { name: "Aquali", rarity: "R", frequency: 0.09 },
        { name: "Carapuce", rarity: "C", frequency: 0.18 },
        { name: "Carabaffe", rarity: "P", frequency: 0.1 },
        { name: "Tortank", rarity: "R", frequency: 0.09 },
        { name: "Obalie_Aquarium", rarity: "L", frequency: 0.0023 }
    ],
    SEABALL: [
        { name: "Tentacruel", rarity: "C", frequency: 0.08759 },
        { name: "Minidraco", rarity: "C", frequency: 0.08759 },
        { name: "Draco", rarity: "P", frequency: 0.06569 },
        { name: "Kaiminus", rarity: "C", frequency: 0.08759 },
        { name: "Crocodil", rarity: "P", frequency: 0.06569 },
        { name: "Aligatueur", rarity: "R", frequency: 0.0438 },
        { name: "Loupio", rarity: "C", frequency: 0.08759 },
        { name: "Lanturn", rarity: "P", frequency: 0.06569 },
        { name: "Démanta", rarity: "R", frequency: 0.0438 },
        { name: "Hyporoi", rarity: "R", frequency: 0.0438 },
        { name: "Hypocéan", rarity: "P", frequency: 0.06569 },
        { name: "Léviator", rarity: "R", frequency: 0.0438 },
        { name: "Roigada", rarity: "R", frequency: 0.0438 },
        { name: "Sancoki", rarity: "C", frequency: 0.08759 },
        { name: "Tritosor", rarity: "P", frequency: 0.06569 },
        { name: "Couaneton", rarity: "C", frequency: 0.08759 },
        { name: "Lakmécygne", rarity: "P", frequency: 0.06569 },
        { name: "Moyade", rarity: "P", frequency: 0.06569 },
        { name: "Mamanbo", rarity: "C", frequency: 0.08759 },
        { name: "Dofin", rarity: "C", frequency: 0.08759 },
        { name: "Superdofin", rarity: "P", frequency: 0.06569 },
        { name: "Sepiatop", rarity: "C", frequency: 0.08759 },
        { name: "Sepiatroce", rarity: "R", frequency: 0.0438 },
        { name: "Nigosier", rarity: "P", frequency: 0.06569 },
        { name: "Corayôme", rarity: "R", frequency: 0.0438 },
        { name: "Embrochet", rarity: "C", frequency: 0.08759 },
        { name: "Hastacuda", rarity: "P", frequency: 0.06569 },
        { name: "Paragruel", rarity: "R", frequency: 0.0438 },
        { name: "Taupikeau", rarity: "C", frequency: 0.08759 },
        { name: "Triopikeau", rarity: "P", frequency: 0.06569 },
        { name: "Obalie_Ocean", rarity: "L", frequency: 0.006 }
    ],
    MOSSBALL: [
        { name: "Axoloto", rarity: "C", frequency: 0.115 },
        { name: "Terraiste", rarity: "P", frequency: 0.0916 },
        { name: "Maraiste", rarity: "P", frequency: 0.0916 },
        { name: "Gobou", rarity: "C", frequency: 0.115 },
        { name: "Flobio", rarity: "P", frequency: 0.0916 },
        { name: "Laggron", rarity: "R", frequency: 0.0578 },
        { name: "Mucuscule", rarity: "C", frequency: 0.115 },
        { name: "Colimucus", rarity: "P", frequency: 0.0916 },
        { name: "Muplodocus", rarity: "R", frequency: 0.0578 },
        { name: "Grenousse", rarity: "C", frequency: 0.115 },
        { name: "Croaporal", rarity: "P", frequency: 0.0916 },
        { name: "Amphinobi", rarity: "R", frequency: 0.0578 },
        { name: "Tritonde", rarity: "C", frequency: 0.115 },
        { name: "Batracné", rarity: "P", frequency: 0.0916 },
        { name: "Crapustule", rarity: "R", frequency: 0.0578 },
        { name: "Cradopaud", rarity: "P", frequency: 0.0916 },
        { name: "Coatox", rarity: "R", frequency: 0.0578 },
        { name: "Rosélia", rarity: "C", frequency: 0.115 },
        { name: "Roserade", rarity: "R", frequency: 0.0578 },
        { name: "Venalgue", rarity: "P", frequency: 0.0916 },
        { name: "Kravarech", rarity: "R", frequency: 0.0578 },
        { name: "Bulbizarre", rarity: "C", frequency: 0.115 },
        { name: "Herbizarre", rarity: "P", frequency: 0.0916 },
        { name: "Florizarre", rarity: "R", frequency: 0.0578 },
        { name: "Keunotor", rarity: "C", frequency: 0.115 },
        { name: "Castorno", rarity: "P", frequency: 0.0916 },
        { name: "Obalie_Marecage", rarity: "L", frequency: 0.001 }
      ],
      TOMBALL :[
        { name: "Polichombr", rarity: "P", frequency: 0.1495 },
        { name: "Téraclope", rarity: "P", frequency: 0.1495 },
        { name: "Feuforêve", rarity: "C", frequency: 0.1345 },
        { name: "Magirêve", rarity: "R", frequency: 0.0995 },
        { name: "Fantominus", rarity: "C", frequency: 0.1345 },
        { name: "Spectrum", rarity: "P", frequency: 0.1495 },
        { name: "Spiritomb", rarity: "R", frequency: 0.0995 },
        { name: "Mysdibule", rarity: "R", frequency: 0.0995 },
        { name: "Munja", rarity: "P", frequency: 0.1495 },
        { name: "Absol", rarity: "R", frequency: 0.0995 },
        { name: "Cornebre", rarity: "C", frequency: 0.1345 },
        { name: "Corboss", rarity: "P", frequency: 0.1495 },
        { name: "Noctali", rarity: "R", frequency: 0.0995 },
        { name: "Darkrai", rarity: "E", frequency: 0.0495 },
        { name: "Mimiqui", rarity: "R", frequency: 0.0995 },
        { name: "Toutombe", rarity: "C", frequency: 0.1345 },
        { name: "Tomberro", rarity: "P", frequency: 0.1495 },
        { name: "Flotte-mèche", rarity: "R", frequency: 0.0995 },
        { name: "Zorua", rarity: "C", frequency: 0.1345 },
        { name: "Zoroark", rarity: "P", frequency: 0.1495 },
        { name: "Obalie_Cimetierre", rarity: "L", frequency: 0.004 }
      ],
      BOOMBALL :[
        { name: "Voltorb", rarity: "C", frequency: 0.14789 },
        { name: "Electrode", rarity: "P", frequency: 0.10526 },
        { name: "Balbuto", rarity: "C", frequency: 0.15789 },
        { name: "Kaorine", rarity: "R", frequency: 0.05263 },
        { name: "Pomdepik", rarity: "C", frequency: 0.14789 },
        { name: "Foretress", rarity: "P", frequency: 0.10526 },
        { name: "Séléroc", rarity: "R", frequency: 0.05263 },
        { name: "Solaroc", rarity: "R", frequency: 0.05263 },
        { name: "Boumata", rarity: "R", frequency: 0.05263 },
        { name: "Volcanion", rarity: "E", frequency: 0.08824 },
        { name: "Météno", rarity: "P", frequency: 0.10000 },
        { name: "Magnéton", rarity: "P", frequency: 0.10000 },
        { name: "Noadkoko", rarity: "P", frequency: 0.10000 },
        { name: "Terhal", rarity: "C", frequency: 0.11765 },
        { name: "Métang", rarity: "P", frequency: 0.10000 },
        { name: "Métalosse", rarity: "R", frequency: 0.05263 },
        { name: "Hexagel", rarity: "P", frequency: 0.10000 },
        { name: "Pierroteknik", rarity: "E", frequency: 0.08824 },
        { name: "Smogo", rarity: "C", frequency: 0.14789 },
        { name: "Smogogo", rarity: "P", frequency: 0.10526 },
        { name: "Obalie_Explosion", rarity: "L", frequency: 0.002 }
      ],
      USINEBALL :[
        { name: "Togedemaru", rarity: "C", frequency: 0.12903 },
        { name: "Raichu", rarity: "R", frequency: 0.05797 },
        { name: "Tic", rarity: "C", frequency: 0.12903 },
        { name: "Clic", rarity: "P", frequency: 0.09677 },
        { name: "Cliticlic", rarity: "R", frequency: 0.05797 },
        { name: "Toxizap", rarity: "P", frequency: 0.09677 },
        { name: "Salarsen", rarity: "R", frequency: 0.05797 },
        { name: "Lainergie", rarity: "P", frequency: 0.09677 },
        { name: "Pharamp", rarity: "R", frequency: 0.05797 },
        { name: "Wattouat", rarity: "C", frequency: 0.12903 },
        { name: "Elekid", rarity: "C", frequency: 0.12903 },
        { name: "Elektek", rarity: "P", frequency: 0.09677 },
        { name: "Elekable", rarity: "R", frequency: 0.05797 },
        { name: "Porygon", rarity: "C", frequency: 0.12903 },
        { name: "Porygon 2", rarity: "P", frequency: 0.09677 },
        { name: "Porygon-Z", rarity: "R", frequency: 0.05797 },
        { name: "Posipi", rarity: "C", frequency: 0.12903 },
        { name: "Négapi", rarity: "C", frequency: 0.12903 },
        { name: "Magnezone", rarity: "R", frequency: 0.05797 },
        { name: "Emolga", rarity: "P", frequency: 0.09677 },
        { name: "Mygavolt", rarity: "P", frequency: 0.09677 },
        { name: "Electhor", rarity: "E", frequency: 0.01935 },
        { name: "Pelage-Sablé", rarity: "R", frequency: 0.05797 },
        { name: "Larvibule", rarity: "C", frequency: 0.12903 },
        { name: "Chrysapile", rarity: "P", frequency: 0.09677 },
        { name: "Lucanon", rarity: "R", frequency: 0.05797 },
        { name: "Obalie_Usine", rarity: "L", frequency: 0.002 },
        { name: "Obalie_Usine", rarity: "L", frequency: 0.003 },
        { name: "Obalie_Usine", rarity: "L", frequency: 0.005 }
      ],
      SERREBALL : [
        { name: "Mimitoss", rarity: "C", frequency: 0.03846 },
        { name: "Aeromite", rarity: "P", frequency: 0.07692 },
        { name: "Chenipotte", rarity: "C", frequency: 0.03846 },
        { name: "Armulys", rarity: "P", frequency: 0.07692 },
        { name: "Blindalys", rarity: "P", frequency: 0.07692 },
        { name: "Charmillon", rarity: "R", frequency: 0.03846 },
        { name: "Papinox", rarity: "R", frequency: 0.03846 },
        { name: "Ningale", rarity: "C", frequency: 0.03846 },
        { name: "Muciole", rarity: "C", frequency: 0.03846 },
        { name: "Lumivole", rarity: "C", frequency: 0.03846 },
        { name: "Cheniselle", rarity: "R", frequency: 0.03846 },
        { name: "Papilord", rarity: "R", frequency: 0.03846 },
        { name: "Apireine", rarity: "R", frequency: 0.03846 },
        { name: "Larveyette", rarity: "C", frequency: 0.03846 },
        { name: "Couverdure", rarity: "P", frequency: 0.07692 },
        { name: "Manternel", rarity: "R", frequency: 0.03846 },
        { name: "Carabing", rarity: "C", frequency: 0.03846 },
        { name: "Lançargot", rarity: "P", frequency: 0.07692 },
        { name: "Escargaume", rarity: "C", frequency: 0.03846 },
        { name: "Lepidonille", rarity: "C", frequency: 0.03846 },
        { name: "Peregrain", rarity: "P", frequency: 0.07692 },
        { name: "Prismillon", rarity: "R", frequency: 0.03846 },
        { name: "Rubombelle", rarity: "P", frequency: 0.07692 },
        { name: "Tissenboule", rarity: "C", frequency: 0.03846 },
        { name: "Filentrappe", rarity: "P", frequency: 0.07692 },
        { name: "Léboulérou", rarity: "C", frequency: 0.03846 },
        { name: "Bérasca", rarity: "P", frequency: 0.07692 },
        { name: "Obalie_Horror", rarity: "L", frequency: 0.0015 },
        { name: "Obalie_Serre", rarity: "L", frequency: 0.0025 }
      ],
      AGRICOBALL : [
        { name: "Germignon", rarity: "C", frequency: 0.116 },
        { name: "Macronium", rarity: "P", frequency: 0.064 },
        { name: "Meganium", rarity: "R", frequency: 0.02 },
        { name: "Shaymin", rarity: "E", frequency: 0.002 },
        { name: "Granivol", rarity: "C", frequency: 0.116 },
        { name: "Floravol", rarity: "P", frequency: 0.064 },
        { name: "Cotovol", rarity: "R", frequency: 0.02 },
        { name: "Tournegrin", rarity: "C", frequency: 0.116 },
        { name: "Héliatronc", rarity: "R", frequency: 0.02 },
        { name: "Joliflor", rarity: "R", frequency: 0.02 },
        { name: "Florges", rarity: "R", frequency: 0.02 },
        { name: "Mimantis", rarity: "C", frequency: 0.116 },
        { name: "Floramantis", rarity: "R", frequency: 0.02 },
        { name: "Doudouvet", rarity: "C", frequency: 0.116 },
        { name: "Farfaduvet", rarity: "P", frequency: 0.064 },
        { name: "Chlorobule", rarity: "C", frequency: 0.116 },
        { name: "Rattata", rarity: "C", frequency: 0.116 },
        { name: "Rattatac", rarity: "P", frequency: 0.064 },
        { name: "Tournicoton", rarity: "C", frequency: 0.116 },
        { name: "Blancoton", rarity: "P", frequency: 0.064 },
        { name: "Lilliterelle", rarity: "C", frequency: 0.116 },
        { name: "Gambex", rarity: "P", frequency: 0.064 },
        { name: "Larvadar", rarity: "C", frequency: 0.116 },
        { name: "Coléodôme", rarity: "P", frequency: 0.064 },
        { name: "Astronelle", rarity: "R", frequency: 0.02 },
        { name: "Phyllali", rarity: "R", frequency: 0.02 },
        { name: "Fouinette", rarity: "C", frequency: 0.116 },
        { name: "Fouinar", rarity: "P", frequency: 0.064 },
        { name: "Coxy", rarity: "C", frequency: 0.116 },
        { name: "Coxyclaque", rarity: "P", frequency: 0.064 },
        { name: "Obalie_Champs", rarity: "L", frequency: 0.004 }
      ],
      ARIDBALL : [
        { name: "Crabicoque", rarity: "C", frequency: 0.14 },
        { name: "Crabaraque", rarity: "P", frequency: 0.05 },
        { name: "Maracachi", rarity: "R", frequency: 0.03 },
        { name: "Baggiguane", rarity: "C", frequency: 0.14 },
        { name: "Baggaïd", rarity: "P", frequency: 0.05 },
        { name: "Cacnea", rarity: "C", frequency: 0.14 },
        { name: "Cacturne", rarity: "P", frequency: 0.05 },
        { name: "Kranoix", rarity: "C", frequency: 0.14 },
        { name: "Vibraninf", rarity: "P", frequency: 0.05 },
        { name: "Libégon", rarity: "R", frequency: 0.03 },
        { name: "Rhinocorne", rarity: "C", frequency: 0.14 },
        { name: "Rhinoferos", rarity: "P", frequency: 0.05 },
        { name: "Galvaran", rarity: "C", frequency: 0.14 },
        { name: "Iguolta", rarity: "P", frequency: 0.05 },
        { name: "Virovent", rarity: "C", frequency: 0.14 },
        { name: "Virevorreur", rarity: "P", frequency: 0.05 },
        { name: "Ferdeter", rarity: "R", frequency: 0.03 },
        { name: "Sabelette", rarity: "C", frequency: 0.14 },
        { name: "Sablaireau", rarity: "P", frequency: 0.05 },
        { name: "Escroco", rarity: "R", frequency: 0.03 },
        { name: "Crocorible", rarity: "P", frequency: 0.05 },
        { name: "Mascaïman", rarity: "C", frequency: 0.14 },
        { name: "Medhyèna", rarity: "C", frequency: 0.14 },
        { name: "Grahèna", rarity: "P", frequency: 0.05 },
        { name: "Vostourno", rarity: "C", frequency: 0.14 },
        { name: "Vaututrice", rarity: "P", frequency: 0.05 },
        { name: "Dunaja", rarity: "P", frequency: 0.05 },
        { name: "Dunaconda", rarity: "R", frequency: 0.03 },
        { name: "Obalie_Desert", rarity: "L", frequency: 0.008 }
      ],
      RUINEBALL : [
        { name: "Archeomire", rarity: "P", frequency: 0.167 },
        { name: "Archeodong", rarity: "R", frequency: 0.0526 },
        { name: "Munna", rarity: "C", frequency: 0.133 },
        { name: "Mushana", rarity: "P", frequency: 0.067 },
        { name: "Nucléos", rarity: "C", frequency: 0.167 },
        { name: "Méios", rarity: "P", frequency: 0.067 },
        { name: "Symbios", rarity: "R", frequency: 0.0526 },
        { name: "Lewsor", rarity: "P", frequency: 0.133 },
        { name: "Neitram", rarity: "R", frequency: 0.0526 },
        { name: "Zarbi", rarity: "C", frequency: 0.133 },
        { name: "Kungfouine", rarity: "C", frequency: 0.133 },
        { name: "Gringolem", rarity: "C", frequency: 0.133 },
        { name: "Golemastoc", rarity: "P", frequency: 0.067 },
        { name: "Hexadron", rarity: "C", frequency: 0.133 },
        { name: "Tutétékri", rarity: "C", frequency: 0.133 },
        { name: "Dolman", rarity: "C", frequency: 0.133 },
        { name: "Natu", rarity: "C", frequency: 0.133 },
        { name: "Xatu", rarity: "P", frequency: 0.067 },
        { name: "Vipélierre", rarity: "C", frequency: 0.133 },
        { name: "Lianaja", rarity: "P", frequency: 0.067 },
        { name: "Tutankafer", rarity: "R", frequency: 0.0526 },
        { name: "Tutafeh", rarity: "C", frequency: 0.133 },
        { name: "Majaspic", rarity: "R", frequency: 0.0526 },
        { name: "Obalie_Ruine", rarity: "L", frequency: 0.002 }
      ],
      ARTICBALL : [
        { name: "Polarhume", rarity: "C", frequency: 0.08621 },
        { name: "Otaria", rarity: "C", frequency: 0.08621 },
        { name: "Lamantine", rarity: "P", frequency: 0.03448 },
        { name: "Artikodin", rarity: "E", frequency: 0.01724 },
        { name: "Farfuret", rarity: "P", frequency: 0.03448 },
        { name: "Dimoret", rarity: "R", frequency: 0.01724 },
        { name: "Marcacrin", rarity: "C", frequency: 0.08621 },
        { name: "Cochignon", rarity: "P", frequency: 0.03448 },
        { name: "Mammochon", rarity: "R", frequency: 0.01724 },
        { name: "Cadoizo", rarity: "R", frequency: 0.01724 },
        { name: "Stalgamin", rarity: "C", frequency: 0.08621 },
        { name: "Momartik", rarity: "R", frequency: 0.01724 },
        { name: "Phogleur", rarity: "P", frequency: 0.03448 },
        { name: "Obalie", rarity: "C", frequency: 0.08621 },
        { name: "Kaimorse", rarity: "R", frequency: 0.01724 },
        { name: "Blizzi", rarity: "C", frequency: 0.08621 },
        { name: "Blizzaroi", rarity: "R", frequency: 0.01724 },
        { name: "Givrali", rarity: "R", frequency: 0.01724 },
        { name: "Grelaçon", rarity: "C", frequency: 0.08621 },
        { name: "Piétacé", rarity: "C", frequency: 0.08621 },
        { name: "Hotte-de-Fer", rarity: "R", frequency: 0.01724 },
        { name: "Frigodo", rarity: "C", frequency: 0.08621 },
        { name: "Cryodo", rarity: "P", frequency: 0.03448 },
        { name: "Glaivodo", rarity: "R", frequency: 0.01724 },
        { name: "Baojian", rarity: "E", frequency: 0.01724 },
        { name: "Frisonille", rarity: "C", frequency: 0.08621 },
        { name: "Beldeneige", rarity: "P", frequency: 0.03448 },
        { name: "M.Glaquette", rarity: "R", frequency: 0.01724 },
        { name: "Bekaglacon", rarity: "P", frequency: 0.03448 },
        { name: "Prinplouf", rarity: "C", frequency: 0.08621 },
        { name: "Pingoléon", rarity: "P", frequency: 0.03448 },
        { name: "Obalie_Glacier", rarity: "L", frequency: 0.002 }
      ],
      MASSBALL : [
        { name: "Cosmovum", rarity: "E", frequency: 0.08 },
        { name: "Galekid", rarity: "C", frequency: 0.2 },
        { name: "Galegon", rarity: "P", frequency: 0.15 },
        { name: "Galeking", rarity: "R", frequency: 0.1 },
        { name: "Drackhaus", rarity: "P", frequency: 0.15 },
        { name: "Draby", rarity: "C", frequency: 0.2 },
        { name: "Bourrinos", rarity: "R", frequency: 0.1 },
        { name: "Wailord", rarity: "R", frequency: 0.05 },
        { name: "Wailmer", rarity: "C", frequency: 0.15 },
        { name: "Balbalèze", rarity: "R", frequency: 0.1 },
        { name: "Seracrawl", rarity: "R", frequency: 0.1 },
        { name: "Charivari", rarity: "C", frequency: 0.2 },
        { name: "Pachyradjah", rarity: "P", frequency: 0.15 },
        { name: "Epine-de-fer", rarity: "R", frequency: 0.05 },
        { name: "Monthracite", rarity: "R", frequency: 0.1 },
        { name: "Trépassable", rarity: "P", frequency: 0.15 },
        { name: "Oniglali", rarity: "R", frequency: 0.1 },
        { name: "Terraiste", rarity: "P", frequency: 0.15 },
        { name: "Flâmigator", rarity: "R", frequency: 0.05 },
        { name: "Dracolosse", rarity: "R", frequency: 0.05 },
        { name: "Embrylex", rarity: "C", frequency: 0.2 },
        { name: "Ymphect", rarity: "P", frequency: 0.15 },
        { name: "Tyranocif", rarity: "R", frequency: 0.05 },
        { name: "Obalie_PoidsLourd", rarity: "L", frequency: 0.002 }
      ],
      CAILLOUXBALL : [
        { name: "Magicarpe", rarity: "C", frequency: 0.143 },
        { name: "Tentacool", rarity: "C", frequency: 0.143 },
        { name: "Wailmer", rarity: "C", frequency: 0.143 },
        { name: "Flingouste", rarity: "C", frequency: 0.143 },
        { name: "Krabby", rarity: "C", frequency: 0.143 },
        { name: "Sabelette", rarity: "C", frequency: 0.143 },
        { name: "Kraknoix", rarity: "C", frequency: 0.143 },
        { name: "Cacnea", rarity: "C", frequency: 0.143 },
        { name: "Balbuto", rarity: "C", frequency: 0.143 },
        { name: "Azumarill", rarity: "R", frequency: 0.05263 },
        { name: "Linéon", rarity: "P", frequency: 0.05263 },
        { name: "Tropius", rarity: "R", frequency: 0.05263 },
        { name: "Kecleon", rarity: "P", frequency: 0.05263 },
        { name: "Absol", rarity: "R", frequency: 0.05263 },
        { name: "Regice", rarity: "E", frequency: 0.015 },
        { name: "Registeel", rarity: "E", frequency: 0.015 },
        { name: "Regirock", rarity: "E", frequency: 0.015 },
        { name: "Regigigas", rarity: "E", frequency: 0.015 },
        { name: "Regieleki", rarity: "E", frequency: 0.015 },
        { name: "Regidrago", rarity: "E", frequency: 0.015 },
        { name: "Obalie_Ancestre", rarity: "L", frequency: 0.004 }
      ],
      FFBALL : [
        { name: "Gobou", rarity: "C", frequency: 0.13953 },
        { name: "Queulorior", rarity: "R", frequency: 0.05263 },
        { name: "Vigoroth", rarity: "P", frequency: 0.10526 },
        { name: "Skitty", rarity: "C", frequency: 0.13953 },
        { name: "Tylton", rarity: "P", frequency: 0.10526 },
        { name: "Mangriff", rarity: "R", frequency: 0.05263 },
        { name: "Altaria", rarity: "R", frequency: 0.05263 },
        { name: "Okéoké", rarity: "C", frequency: 0.13953 },
        { name: "Spinda", rarity: "P", frequency: 0.10526 },
        { name: "Medhyena", rarity: "C", frequency: 0.13953 },
        { name: "Poussifeu", rarity: "C", frequency: 0.13953 },
        { name: "Parecool", rarity: "C", frequency: 0.13953 },
        { name: "Spoink", rarity: "C", frequency: 0.13953 },
        { name: "Groret", rarity: "P", frequency: 0.10526 },
        { name: "Delcatty", rarity: "P", frequency: 0.10526 },
        { name: "Morphéo", rarity: "R", frequency: 0.05263 },
        { name: "Galifeu", rarity: "P", frequency: 0.10526 },
        { name: "Nénupiot", rarity: "C", frequency: 0.13953 },
        { name: "Dynavolt", rarity: "C", frequency: 0.13953 },
        { name: "Latias", rarity: "E", frequency: 0.03 },
        { name: "Latios", rarity: "E", frequency: 0.03},
        { name: "Obalie_Volant", rarity: "L", frequency: 0.0025 }
      ],
      ROCKETBALL : [
        { name: "Rattata", rarity: "C", frequency: 0.11891 },
        { name: "Abo", rarity: "C", frequency: 0.11891 },
        { name: "Arbok", rarity: "R", frequency: 0.05263 },
        { name: "Smogo", rarity: "C", frequency: 0.11891 },
        { name: "Smogogo", rarity: "P", frequency: 0.04656 },
        { name: "Soporifik", rarity: "C", frequency: 0.11891 },
        { name: "Miaouss", rarity: "C", frequency: 0.11891 },
        { name: "Persian", rarity: "P", frequency: 0.04656 },
        { name: "Mewtwo", rarity: "E", frequency: 0.0117 },
        { name: "Ramoloss", rarity: "C", frequency: 0.11891 },
        { name: "Métamorph", rarity: "R", frequency: 0.05263 },
        { name: "Obalie_Rocket", rarity: "L", frequency: 0.003 },
      ],
      TOURBILESBALL : [
        { name: "Norsferapti", rarity: "C", frequency: 0.1477 },
        { name: "Nosferalto", rarity: "P", frequency: 0.07385 },
        { name: "Otaria", rarity: "C", frequency: 0.1477 },
        { name: "Krabby", rarity: "C", frequency: 0.1477 },
        { name: "Tentacool", rarity: "C", frequency: 0.1477 },
        { name: "Tentacruel", rarity: "P", frequency: 0.07385 },
        { name: "Hypotrempe", rarity: "C", frequency: 0.1477 },
        { name: "Magicarpe", rarity: "C", frequency: 0.1477 },
        { name: "Lugia", rarity: "E", frequency: 0.02 },
        { name: "Obalie_Ile", rarity: "L", frequency: 0.004 }
      ],
      CARILLONBALL : [
        { name: "Rattata", rarity: "C", frequency: 0.1754 },
        { name: "Fantominus", rarity: "C", frequency: 0.1754 },
        { name: "Zigzaton", rarity: "C", frequency: 0.1754 },
        { name: "Spinda", rarity: "P", frequency: 0.13155 },
        { name: "Meditikka", rarity: "C", frequency: 0.1754 },
        { name: "Pijako", rarity: "R", frequency: 0.04385 },
        { name: "Ho-Oh", rarity: "E", frequency: 0.02 },
        { name: "Obalie_Carillon", rarity: "L", frequency: 0.004 },
      ],
      CENDREEBALL : [
        { name: "Suicune", rarity: "E", frequency: 0.04 },
        { name: "Raikou", rarity: "E", frequency: 0.04 },
        { name: "Entei", rarity: "E", frequency: 0.04 },
        { name: "Rattata", rarity: "C", frequency: 0.1875 },
        { name: "Rattatac", rarity: "P", frequency: 0.125 },
        { name: "Nosferapti", rarity: "C", frequency: 0.1875 },
        { name: "Smogo", rarity: "C", frequency: 0.1875 },
        { name: "Krabby", rarity: "C", frequency: 0.1875 },
        { name: "Caractroc", rarity: "R", frequency: 0.125 },
        { name: "Magmar", rarity: "P", frequency: 0.0625 },
        { name: "Smogogo", rarity: "P", frequency: 0.0625 },
        { name: "Zigzaton", rarity: "C", frequency: 0.1875 },
        { name: "Spinda", rarity: "P", frequency: 0.0625 },
        { name: "Méditikka", rarity: "C", frequency: 0.1875 },
        { name: "Pijako", rarity: "R", frequency: 0.125 },
        { name: "Obalie_Cendree", rarity: "L", frequency: 0.004 }
      ],
      DONJONBALL : [
        { name: "Bulbizarre", rarity: "C", frequency: 0.11256 },
        { name: "Salamèche", rarity: "C", frequency: 0.11256 },
        { name: "Carapuce", rarity: "C", frequency: 0.11256 },
        { name: "Pikachu", rarity: "E", frequency: 0.06 },
        { name: "Miaouss", rarity: "C", frequency: 0.11256 },
        { name: "Psykokwak", rarity: "C", frequency: 0.11256 },
        { name: "Machoc", rarity: "C", frequency: 0.11256 },
        { name: "Osselait", rarity: "C", frequency: 0.11256 },
        { name: "Evoli", rarity: "C", frequency: 0.11256 },
        { name: "Germingnon", rarity: "C", frequency: 0.11256 },
        { name: "Hericendre", rarity: "C", frequency: 0.11256 },
        { name: "Kaiminus", rarity: "C", frequency: 0.11256 },
        { name: "Arcko", rarity: "C", frequency: 0.11256 },
        { name: "Poussifeu", rarity: "C", frequency: 0.11256 },
        { name: "Gobou", rarity: "C", frequency: 0.11256 },
        { name: "Skitty", rarity: "C", frequency: 0.11256 },
        { name: "Gruikui", rarity: "C", frequency: 0.11256 },
        { name: "Vipélierre", rarity: "C", frequency: 0.11256 },
        { name: "Moustillon", rarity: "C", frequency: 0.11256 },
        { name: "Coupenotte", rarity: "C", frequency: 0.11256 },
        { name: "Obalie_Donjon", rarity: "L", frequency: 0.018 }
      ],
      GTBALL : [
        { name: "Groudon", rarity: "E", frequency: 0.06 },
        { name: "Tylton", rarity: "C", frequency: 0.1537 },
        { name: "Seviper", rarity: "P", frequency: 0.0978 },
        { name: "Nenupiot", rarity: "C", frequency: 0.1537 },
        { name: "Pifeuil", rarity: "C", frequency: 0.1537 },
        { name: "Rondoudou", rarity: "C", frequency: 0.1537 },
        { name: "Goelise", rarity: "C", frequency: 0.1537 },
        { name: "Nirondelle", rarity: "C", frequency: 0.1537 },
        { name: "Skitty", rarity: "C", frequency: 0.1537 },
        { name: "Ningale", rarity: "C", frequency: 0.1537 },
        { name: "Chuchmur", rarity: "C", frequency: 0.1537 },
        { name: "Dynavolt", rarity: "C", frequency: 0.1537 },
        { name: "Obalie_GT", rarity: "L", frequency: 0.008 }
      ],
      GMBALL : [
        { name: "Wailmer", rarity: "C", frequency: 0.18605 },
        { name: "Tentacool", rarity: "C", frequency: 0.18605 },
        { name: "Kyogre", rarity: "E", frequency: 0.04},
        { name: "Magicarpe", rarity: "C", frequency: 0.18605 },
        { name: "Viskuse", rarity: "C", frequency: 0.08255 },
        { name: "Krabby", rarity: "C", frequency: 0.18605 },
        { name: "Goelise", rarity: "C", frequency: 0.18605 },
        { name: "Bekipan", rarity: "P", frequency: 0.08255 },
        { name: "Coquiperl", rarity: "C", frequency: 0.18605 },
        { name: "Loupio", rarity: "C", frequency: 0.18605 },
        { name: "Carvannha", rarity: "P", frequency: 0.08255 },
        { name: "Obalie_GM", rarity: "L", frequency: 0.0038 }
      ],
      CELESTEBALL : [
        { name: "Rayquaza", rarity: "E", frequency: 0.025 },
        { name: "Deoxys", rarity: "E", frequency: 0.025 },
        { name: "Nosferalto", rarity: "C", frequency: 0.2 },
        { name: "Mysdibule", rarity: "R", frequency: 0.1 },
        { name: "Ténéfix", rarity: "R", frequency: 0.1 },
        { name: "Kaorine", rarity: "R", frequency: 0.1 },
        { name: "Téraclope", rarity: "P", frequency: 0.15 },
        { name: "Branette", rarity: "R", frequency: 0.1 },
        { name: "Altaria", rarity: "R", frequency: 0.1 },
        { name: "Migalos", rarity: "R", frequency: 0.1 },
        { name: "Obalie_Celeste", rarity: "L", frequency: 0.0035 }
      ],
      ROBOTBALL : [
        { name: "Genesect", rarity: "E", frequency: 0.065 },
        { name: "Zygarde", rarity: "E", frequency: 0.065 },
        { name: "Magearna", rarity: "E", frequency: 0.065},
        { name: "Neitram", rarity: "R", frequency: 0.14286 },
        { name: "Lewsor", rarity: "P", frequency: 0.125 },
        { name: "Roue-de-Fer", rarity: "R", frequency: 0.14286 },
        { name: "Têtes-de-Fer", rarity: "R", frequency: 0.14286 },
        { name: "Mite-de-Fer", rarity: "R", frequency: 0.14286 },
        { name: "Tic", rarity: "C", frequency: 0.23077 },
        { name: "Clic", rarity: "P", frequency: 0.16667 },
        { name: "Cliticlic", rarity: "R", frequency: 0.14286 },
        { name: "Magnéti", rarity: "C", frequency: 0.23077 },
        { name: "Magnéton", rarity: "P", frequency: 0.16667 },
        { name: "Magnézone", rarity: "R", frequency: 0.14286 },
        { name: "Vrombi", rarity: "C", frequency: 0.23077 },
        { name: "Vrombotor", rarity: "P", frequency: 0.16667 },
        { name: "Airmure", rarity: "R", frequency: 0.14286 },
        { name: "Obalie_Robot", rarity: "L", frequency: 0.004 }
      ],
      LACBALL : [
        { name: "Créhelf", rarity: "E", frequency: 0.035 },
        { name: "Créfadet", rarity: "E", frequency: 0.035 },
        { name: "Créfollet", rarity: "E", frequency: 0.035 },
        { name: "Farfuret", rarity: "C", frequency: 0.2143 },
        { name: "Korillon", rarity: "P", frequency: 0.1111 },
        { name: "Psykokwak", rarity: "C", frequency: 0.2143 },
        { name: "Akwakwak", rarity: "P", frequency: 0.1111 },
        { name: "Poissirène", rarity: "C", frequency: 0.2143 },
        { name: "Excelangue", rarity: "R", frequency: 0.0714 },
        { name: "Magicarpe", rarity: "C", frequency: 0.2143 },
        { name: "Qulbutoké", rarity: "R", frequency: 0.0714 },
        { name: "Arakdo", rarity: "C", frequency: 0.2143 },
        { name: "Etourvol", rarity: "P", frequency: 0.1111 },
        { name: "Solaroc", rarity: "R", frequency: 0.0714 },
        { name: "Seleroc", rarity: "R", frequency: 0.0714 },
        { name: "Obalie_Lac", rarity: "L", frequency: 0.004 },
      ],
      LAMEBALL : [
        { name: "Viridium", rarity: "E", frequency: 0.045 },
        { name: "Terrakium", rarity: "E", frequency: 0.045 },
        { name: "Cobaltium", rarity: "E", frequency: 0.045 },
        { name: "Keldeo", rarity: "E", frequency: 0.045 },
        { name: "Géolithe", rarity: "P", frequency: 0.15 },
        { name: "Chovsourir", rarity: "C", frequency: 0.175 },
        { name: "Coupenotte", rarity: "C", frequency: 0.175 },
        { name: "Rototaupe", rarity: "C", frequency: 0.175 },
        { name: "Poichigeon", rarity: "C", frequency: 0.175 },
        { name: "Charpenti", rarity: "C", frequency: 0.175 },
        { name: "Tritonde", rarity: "C", frequency: 0.175 },
        { name: "Nanméouïe", rarity: "R", frequency: 0.1 },
        { name: "Solochi", rarity: "C", frequency: 0.15 },
        { name: "Kungfouine", rarity: "C", frequency: 0.15 },
        { name: "Fermite", rarity: "R", frequency: 0.1 },
        { name: "Aflamanoir", rarity: "R", frequency: 0.1 },
        { name: "Furaiglon", rarity: "C", frequency: 0.15 },
        { name: "Vostourno", rarity: "C", frequency: 0.15 },
        { name: "Incisache", rarity: "P", frequency: 0.125 },
        { name: "Obalie_Lame", rarity: "L", frequency: 0.0065 },
      ],
      DIEUXBALL : [
        { name: "Fulguris", rarity: "E", frequency: 0.02 },
        { name: "Boreas", rarity: "E", frequency: 0.02 },
        { name: "Demeteros", rarity: "E", frequency: 0.02 },
        { name: "Feuillajou", rarity: "C", frequency: 0.1 },
        { name: "Feuilloutan", rarity: "P", frequency: 0.05 },
        { name: "Flamajou", rarity: "C", frequency: 0.1 },
        { name: "Flamoutan", rarity: "P", frequency: 0.05 },
        { name: "Flotajou", rarity: "C", frequency: 0.1 },
        { name: "Flotoutan", rarity: "P", frequency: 0.05 },
        { name: "Batracné", rarity: "P", frequency: 0.05 },
        { name: "Diamat", rarity: "P", frequency: 0.05 },
        { name: "Scalpion", rarity: "C", frequency: 0.1 },
        { name: "Scalproie", rarity: "R", frequency: 0.025 },
        { name: "Tranchodon", rarity: "R", frequency: 0.025 },
        { name: "Trioxhydre", rarity: "R", frequency: 0.025 },
        { name: "Obalie_Dieux", rarity: "L", frequency: 0.0045 }
      ],
      CYCLOPEEBALL : [
        { name: "Reshiram", rarity: "E", frequency: 0.02 },
        { name: "Zekrom", rarity: "E", frequency: 0.02},
        { name: "Kyurem", rarity: "E", frequency: 0.02 },
        { name: "Saquedeneu", rarity: "P", frequency: 0.12 },
        { name: "Hélédelle", rarity: "P", frequency: 0.12 },
        { name: "Séléroc", rarity: "R", frequency: 0.08 },
        { name: "Solaroc", rarity: "R", frequency: 0.08 },
        { name: "Absol", rarity: "R", frequency: 0.08 },
        { name: "Grodrive", rarity: "P", frequency: 0.12 },
        { name: "Sorboul", rarity: "P", frequency: 0.12 },
        { name: "Cadoizo", rarity: "R", frequency: 0.08 },
        { name: "Nostenfer", rarity: "R", frequency: 0.08 },
        { name: "Bouldeneu", rarity: "R", frequency: 0.08 },
        { name: "Sorbouboul", rarity: "R", frequency: 0.08 },
        { name: "Emolga", rarity: "P", frequency: 0.12 },
        { name: "Cochignon", rarity: "P", frequency: 0.12 },
        { name: "Obalie_Cyclopee", rarity: "L", frequency: 0.001 }
      ],
      XBALL : [
        { name: "Cabriolaine", rarity: "C", frequency: 0.20255 },
        { name: "Chevroum", rarity: "P", frequency: 0.13141 },
        { name: "Feuillajou", rarity: "C", frequency: 0.20255 },
        { name: "Feuiloutan", rarity: "P", frequency: 0.13141 },
        { name: "Chlorobule", rarity: "C", frequency: 0.20255 },
        { name: "Fragilady", rarity: "P", frequency: 0.13141 },
        { name: "Cocotine", rarity: "P", frequency: 0.13141},
        { name: "Xerneas", rarity: "E", frequency: 0.02 },
        { name: "Obalie_Xerneas", rarity: "L", frequency: 0.004 },
      ],
      AETHERBALL : [
        { name: "Type:0", rarity: "E", frequency: 0.015 },
        { name: "Silvallié", rarity: "E", frequency: 0.015 },
        { name: "Millobelus", rarity: "R", frequency: 0.08696 },
        { name: "Kaorine", rarity: "P", frequency: 0.04348 },
        { name: "Ponchien", rarity: "P", frequency: 0.04348 },
        { name: "Denticrisse", rarity: "C", frequency: 0.21739 },
        { name: "Colimucus", rarity: "P", frequency: 0.04348 },
        { name: "Porygon-Z", rarity: "R", frequency: 0.08696 },
        { name: "Luminéon", rarity: "P", frequency: 0.04348 },
        { name: "Flagadoss", rarity: "P", frequency: 0.04348 },
        { name: "Obalie_Aether", rarity: "L", frequency: 0.0025 },
      ],
      GARDIENBALL : [
        { name: "Tokorico", rarity: "E", frequency: 0.035 },
        { name: "Tokopiyon", rarity: "E", frequency: 0.035 },
        { name: "Tokotoro", rarity: "E", frequency: 0.035 },
        { name: "Tokopisco", rarity: "E", frequency: 0.035 },
        { name: "Plumeline", rarity: "P", frequency: 0.0833 },
        { name: "Rubombelle", rarity: "P", frequency: 0.0833 },
        { name: "Rocabot", rarity: "C", frequency: 0.125 },
        { name: "Lougaroc", rarity: "R", frequency: 0.0417 },
        { name: "Araqua", rarity: "C", frequency: 0.125 },
        { name: "Tarenbulle", rarity: "P", frequency: 0.0625 },
        { name: "Tritox", rarity: "C", frequency: 0.125 },
        { name: "Malamandre", rarity: "P", frequency: 0.0625 },
        { name: "Nounourson", rarity: "R", frequency: 0.0417 },
        { name: "Concombaffe", rarity: "C", frequency: 0.125 },
        { name: "Sovkipou", rarity: "C", frequency: 0.125 },
        { name: "Sarmuraï", rarity: "R", frequency: 0.0417 },
        { name: "Bacabouh", rarity: "C", frequency: 0.125 },
        { name: "Brindibou", rarity: "C", frequency: 0.125 },
        { name: "Efflèche", rarity: "P", frequency: 0.0625 },
        { name: "Archéduc", rarity: "R", frequency: 0.0417 },
        { name: "Obalie_Gardien", rarity: "L", frequency: 0.0025 }
      ],
      DIURNEBALL : [
        { name: "Solgaleo", rarity: "E", frequency: 0.045 },
        { name: "Lunala", rarity: "E", frequency: 0.045 },
        { name: "Bébécaille", rarity: "C", frequency: 0.25 },
        { name: "Ecaïd", rarity: "P", frequency: 0.15 },
        { name: "Ekaïser", rarity: "R", frequency: 0.1 },
        { name: "Otaquin", rarity: "C", frequency: 0.25 },
        { name: "Otarlette", rarity: "P", frequency: 0.15 },
        { name: "Oratoria", rarity: "R", frequency: 0.1 },
        { name: "Lampignon", rarity: "P", frequency: 0.15 },
        { name: "Gouroutan", rarity: "R", frequency: 0.1 },
        { name: "Quatermac", rarity: "R", frequency: 0.1 },
        { name: "Dodoala", rarity: "P", frequency: 0.15 },
        { name: "Draïeul", rarity: "R", frequency: 0.1 },
        { name: "Sinistrail", rarity: "P", frequency: 0.15 },
        { name: "Obalie_JourNuit", rarity: "L", frequency: 0.0045 }
      ],
      UCBALL : [
        { name: "Zéroïd", rarity: "E", frequency: 0.07 },
        { name: "Mouscoto", rarity: "E", frequency: 0.07 },
        { name: "Câblifière", rarity: "E", frequency: 0.07 },
        { name: "Cancrelove", rarity: "E", frequency: 0.07 },
        { name: "Engloutyran", rarity: "E", frequency: 0.07 },
        { name: "Bamboiselle", rarity: "E", frequency: 0.07 },
        { name: "Katagami", rarity: "E", frequency: 0.07 },
        { name: "Vémini", rarity: "E", frequency: 0.07 },
        { name: "Mandrillon", rarity: "E", frequency: 0.05 },
        { name: "PierroTeknik", rarity: "E", frequency: 0.07 },
        { name: "Ama-Ama", rarity: "E", frequency: 0.07 },
        { name: "Necrozma", rarity: "E", frequency: 0.07 },
        { name: "Obalie_Uc", rarity: "L", frequency: 0.0055 },
      ],
      CHEVALIERBALL : [
        { name: "Zacian", rarity: "E", frequency: 0.055 },
        { name: "Zamazenta", rarity: "E", frequency: 0.055 },
        { name: "Ethernatos", rarity: "E", frequency: 0.055 },
        { name: "Lancargot", rarity: "R", frequency: 0.15 },
        { name: "Garde-de-Fer", rarity: "R", frequency: 0.15 },
        { name: "Monorpale", rarity: "C", frequency: 0.2 },
        { name: "Dimoclès", rarity: "P", frequency: 0.15 },
        { name: "Exagide", rarity: "R", frequency: 0.15 },
        { name: "Carabing", rarity: "C", frequency: 0.2 },
        { name: "Charbambin", rarity: "P", frequency: 0.15 },
        { name: "Carmadura", rarity: "R", frequency: 0.15 },
        { name: "Malavalame", rarity: "R", frequency: 0.15 },
        { name: "Moustillon", rarity: "C", frequency: 0.2 },
        { name: "Mateloutre", rarity: "P", frequency: 0.15 },
        { name: "Clamiral", rarity: "R", frequency: 0.15 },
        { name: "Marisson", rarity: "C", frequency: 0.2 },
        { name: "Boguérisse", rarity: "P", frequency: 0.15 },
        { name: "Blindépique", rarity: "R", frequency: 0.15 },
        { name: "Obalie_Chevalier", rarity: "L", frequency: 0.023 }
      ],
      MYSTRESTBALL : [
        { name: "Zarude", rarity: "E", frequency: 0.01 },
        { name: "Celebi", rarity: "E", frequency: 0.01 },
        { name: "Dinglu", rarity: "E", frequency: 0.01 },
        { name: "Vert de fer", rarity: "E", frequency: 0.01 },
        { name: "Chongijan", rarity: "E", frequency: 0.01 },
        { name: "Poussacha", rarity: "C", frequency: 0.15 },
        { name: "Matourgeon", rarity: "P", frequency: 0.1 },
        { name: "Miascarade", rarity: "R", frequency: 0.05 },
        { name: "Cerfrousse", rarity: "C", frequency: 0.15 },
        { name: "Chapotus", rarity: "P", frequency: 0.1 },
        { name: "Sorcilence", rarity: "R", frequency: 0.05 },
        { name: "Grimalin", rarity: "C", frequency: 0.15 },
        { name: "Fourbelin", rarity: "P", frequency: 0.1 },
        { name: "Angoliath", rarity: "R", frequency: 0.05 },
        { name: "Obalie_ForestM", rarity: "L", frequency: 0.004 }
      ],
      COUROBALL : [
        { name: "Blizzeval", rarity: "E", frequency: 0.013 },
        { name: "Spectreval", rarity: "E", frequency: 0.013 },
        { name: "Sylveroy", rarity: "E", frequency: 0.013 },
        { name: "Larméléon", rarity: "C", frequency: 0.21428 },
        { name: "Arrozard", rarity: "P", frequency: 0.10714 },
        { name: "Lézargus", rarity: "R", frequency: 0.07142 },
        { name: "Ixon", rarity: "R", frequency: 0.07142 },
        { name: "Berserkatt", rarity: "P", frequency: 0.10714 },
        { name: "Duralugon", rarity: "R", frequency: 0.07142 },
        { name: "Cerbyllin", rarity: "R", frequency: 0.07142 },
        { name: "Fantyrm", rarity: "C", frequency: 0.21428 },
        { name: "Dispareptil", rarity: "P", frequency: 0.10714 },
        { name: "Lanssorien", rarity: "R", frequency: 0.07142 },
        { name: "Obalie_Cheval", rarity: "L", frequency: 0.004 }
      ],
      PALDEBALL : [
        { name: "Koraidon", rarity: "E", frequency: 0.055 },
        { name: "Miraidon", rarity: "E", frequency: 0.055 },
        { name: "Coiffeton", rarity: "C", frequency: 0.2 },
        { name: "Canarbello", rarity: "P", frequency: 0.15 },
        { name: "Palmaval", rarity: "R", frequency: 0.5 },
        { name: "Motorizard", rarity: "P", frequency: 0.15 },
        { name: "Campagnol", rarity: "C", frequency: 0.2 },
        { name: "Famignol", rarity: "P", frequency: 0.15 },
        { name: "Grondogue", rarity: "C", frequency: 0.2 },
        { name: "Dogrino", rarity: "P", frequency: 0.15 },
        { name: "Scalpereur", rarity: "R", frequency: 0.05 },
        { name: "Gromago", rarity: "R", frequency: 0.05 },
        { name: "Germéclat", rarity: "P", frequency: 0.15 },
        { name: "Floréclat", rarity: "R", frequency: 0.05 },
        { name: "Obalie_Moto", rarity: "L", frequency: 0.019 }
      ],
      SWEETIEBALL : [
        { name: "Jirachi", rarity: "E", frequency: 0.015 },
        { name: "Cresselia", rarity: "E", frequency: 0.015 },
        { name: "Victini", rarity: "E", frequency: 0.015 },
        { name: "Mélofée", rarity: "P", frequency: 0.142 },
        { name: "Mélodelfe", rarity: "R", frequency: 0.071 },
        { name: "Leveinard", rarity: "P", frequency: 0.120 },
        { name: "Leuphorie", rarity: "R", frequency: 0.060 },
        { name: "Ptiravi", rarity: "C", frequency: 0.200 },
        { name: "Togetic", rarity: "C", frequency: 0.142 },
        { name: "Togekiss", rarity: "P", frequency: 0.071 },
        { name: "Nymphali", rarity: "R", frequency: 0.071 },
        { name: "Obalie_Bienfesance", rarity: "L", frequency: 0.002 }
      ],
      COURONNEEBALL : [
        { name: "Palkia", rarity: "E", frequency: 0.015 },
        { name: "Dialga", rarity: "E", frequency: 0.015 },
        { name: "Giratina", rarity: "E", frequency: 0.015 },
        { name: "Mélofée", rarity: "P", frequency: 0.11811 },
        { name: "Nosferalto", rarity: "R", frequency: 0.0796 },
        { name: "Machopeur", rarity: "P", frequency: 0.11811 },
        { name: "Gravalanch", rarity: "P", frequency: 0.11811 },
        { name: "Charmina", rarity: "P", frequency: 0.11811 },
        { name: "Korillon", rarity: "P", frequency: 0.11811 },
        { name: "Eoko", rarity: "R", frequency: 0.0796 },
        { name: "Archéodong", rarity: "R", frequency: 0.0796 },
        { name: "Blizzi", rarity: "C", frequency: 0.17441 },
        { name: "Blizzaroi", rarity: "R", frequency: 0.0796 },
        { name: "Noarfang", rarity: "R", frequency: 0.0796 },
        { name: "Ramboum", rarity: "P", frequency: 0.11811 },
        { name: "Obalie_Couronnee", rarity: "L", frequency: 0.004 }
      ]
    };

  let cumulativeFrequency = 0; // on initialise la variable cumulativeFrequency a 0
  let pokeid = 0;               // on initialise la variable pokeid a 0
  const pokemonList = combinedList[region]; // on initialise la liste avec seulement la liste par rapport a l'argument choisi
  while (cumulativeFrequency < 1) {         // tant que la variable cumulativeFrequency est inferieur a 1
    pokeid = Math.floor(Math.random() * pokemonList.length); //on prend un nombre aleatoire entre 0 et la longueur de la liste
    cumulativeFrequency += pokemonList[pokeid].frequency;    //puis on additionne la frequence du pokemon a la frequence cumulée
  }

  return pokemonList[pokeid];  // on retourne le pokemon choisi
}


module.exports.ball = ball;  // on exporte la fonction ball


